# Generated by Django 4.2.15 on 2025-07-25 02:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Operacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_operacao', models.CharField(choices=[('soma', 'Soma'), ('subtracao', 'Subtração'), ('multiplicacao', 'Multiplicação'), ('divisao', 'Divisão')], max_length=20, verbose_name='Tipo de Operação')),
                ('numero1', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Primeiro Número')),
                ('numero2', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Segundo Número')),
                ('resultado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Resultado')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Operação',
                'verbose_name_plural': 'Operações',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
