# Generated by Django 4.2.15 on 2025-07-25 12:45

from django.db import migrations, models


def set_parametros_default(apps, schema_editor):
    # Para cada operação existente, converte numero1 e numero2 para o formato JSON
    Operacao = apps.get_model('calculadora', 'Operacao')
    for op in Operacao.objects.all():
        op.parametros = f'[{op.numero1}, {op.numero2}]'
        op.save()


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacao',
            name='parametros',
            field=models.TextField(default='[0, 0]', verbose_name='Parâmetros'),
            preserve_default=False,
        ),
        migrations.RunPython(set_parametros_default, reverse_code=migrations.RunPython.noop),
    ]
