# Generated by Django 4.2.15 on 2025-07-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0002_parametros_nullable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operacao',
            name='numero1',
        ),
        migrations.RemoveField(
            model_name='operacao',
            name='numero2',
        ),
        migrations.AlterField(
            model_name='operacao',
            name='parametros',
            field=models.TextField(help_text='Parâmetros da operação em formato JSON (ex: [10.5, 20.3])', verbose_name='Parâmetros'),
        ),
    ]
