# Generated by Django 4.2.15 on 2025-07-25 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0003_remove_campos_antigos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacao',
            name='parametros',
            field=models.TextField(verbose_name='Parâmetros'),
        ),
    ]
